{
  "labels": {
    "APP_VENDOR": "Camunda",
    "ADMIN_APP": "Admin",
    "TASKLIST_APP": "Tasklist",
    "COCKPIT_APP": "Cockpit",
    "TOGGLE_NAVIGATION": "Alternar de navegação",
    "SUBMIT": "Enviar",
    "SAVE": "Salvar",
    "START": "Iniciar",
    "ABORT": "Abortar",
    "CLOSE": "Fechar",
    "CANCEL": "Cancelar",
    "BACK": "Voltar",
    "DELETE": "Apagar",
    "SET": "Atribuir",
    "CHANGE": "Mudar",
    "TASK": "Task",
    "FILTER": "Filtro",
    "TASKS": "Tarefas",
    "FILTERS": "Filtros",
    "LOADING": "Carregando...",
    "REQUIRED_FIELD": "Campo obrigatório",
    "REQUIRED_INTEGER_FIELD": "O valor deve ser um número inteiro",
    "REQUIRED_HEX_COLOR_FIELD": "O valor deve ser uma cor hexadecimal",
    "PROCESS_DEFINITION": "Definição do processo",
    "PROCESS_INSTANCE": "Instância do processo",
    "MANAGE_ACCOUNT": "Gerencie sua conta",
    "ASC": "Ascendente",
    "DESC": "Descendente",
    "BOOLEAN": "Boolean",
    "SHORT": "Short",
    "INTEGER": "Integer",
    "LONG": "Long",
    "DOUBLE": "Double",
    "DATE": "Date",
    "STRING": "String",
    "AUTH_LOGOUT_SUCCESSFUL": "Logout realizado com sucesso",
    "AUTH_LOGOUT_THANKS": "Obrigado por usar o Camunda hoje. Tenha um(a) ótimo(a) {{dayContext}}!",
    "AUTH_DAY_CONTEXT_MORNING": "manhã",
    "AUTH_DAY_CONTEXT_DAY": "dia",
    "AUTH_DAY_CONTEXT_AFTERNOON": "tarde",
    "AUTH_DAY_CONTEXT_EVENING": "tarde",
    "AUTH_DAY_CONTEXT_NIGHT": "noite",
    "AUTH_DAY_CONTEXT_WEEKEND": "final de semana",
    "AUTH_FAILED_TO_DISPLAY_RESOURCE": "Falha ao exibir recursos",
    "AUTH_AUTHENTICATION_FAILED": "Falha na autenticação. Sua sessão pode ter expirado, você precisa fazer o login novamente.",
    "PAGE_LOGIN_ERROR_MSG": "Credenciais erradas ou falta de direitos de acesso à aplicação",
    "PAGE_LOGIN_USERNAME": "Usúario",
    "PAGE_LOGIN_PASSWORD": "Senha",
    "PAGE_LOGIN_PLEASE_SIGN_IN": "Informe seu usuário e senha",
    "PAGE_LOGIN_SIGN_IN_ACTION": "Entrar",
    "PAGE_LOGIN_FAILED": "Login falhou",
    "SIGN_OUT_ACTION": "Sair",
    "MY_PROFILE": "Meu perfil",
    "DIRECTIVE_ENGINE_SELECT_TOOLTIP": "Se você tiver vários motores em execução, você pode selecionar o mecanismo de processo aqui. Os dados exibidos neste aplicativo são baseados apenas no motor selecionado.",
    "DIRECTIVE_ENGINE_SELECT_STATUS_NOT_FOUND": "Não encontrado",
    "DIRECTIVE_ENGINE_SELECT_MESSAGE_NOT_FOUND": "O mecanismo de processo que você está tentando acessar não existe",
    "DIRECTIVE_INPLACE_TEXTFIELD_ERROR_MSG": "Você deve especificar uma propriedade do contexto para ser editável",
    "PAGES_STATUS_SERVER_ERROR": "Erro no servidor",
    "PAGES_MSG_SERVER_ERROR": "O servidor encontrou um erro interno. Tente recarregar a página ou logar e deslogar da aplicação.",
    "PAGES_STATUS_REQUEST_TIMEOUT": "Tempo limite de requisição",
    "PAGES_MSG_REQUEST_TIMEOUT": "YSua requisição expirou. Tente atualizar a página.",
    "PAGES_STATUS_ACCESS_DENIED": "Acesso negado",
    "PAGES_MSG_ACCESS_DENIED": "Você não está autorizado para {{missingAuths}}.",
    "PAGES_MSG_ACCESS_DENIED_RESOURCE_ID": "Você não está autorizado para {{permissionName}} {{resourceName}} {{resourceId}}.",
    "PAGES_MSG_ACTION_DENIED": "A ação executada foi negada pelo servidor. Tente atualizar a página.",
    "PAGES_STATUS_NOT_FOUND": "Não encontrado",
    "PAGES_MSG_NOT_FOUND": "Não foi possível encontrar um recurso solicitado.",
    "PAGES_STATUS_COMMUNICATION_ERROR": "Erro de comunicação",
    "PAGES_MSG_COMMUNICATION_ERROR": "O aplicativo recebeu uma resposta inesperada {{status}} do servidor. Tente atualizar a página ou entrar e sair do aplicativo.",
    "PAGES_MSG_ENGINE_NOT_EXISTS": "O mecanismo de processo que você está tentando acessar não existe.",
    "SERVICES_RESOURCE_RESOLVER_ID_NOT_FOUND": "{{resourceName}} com ID {{id}} não existe.",
    "SERVICES_RESOURCE_RESOLVER_AUTH_FAILED": "Falha na autenticação. Sua sessão pode ter expirado, você precisa fazer o login novamente.",
    "SERVICES_RESOURCE_RESOLVER_RECEIVED_STATUS": "Status {{status}} recebido do servidor.",
    "SERVICES_RESOURCE_RESOLVER_DISPLAY_FAILED": "Falha ao exibir {{resourceName}}",
    "SERVICES_RESOURCE_RESOLVER_NO_PROMISE": "Nenhuma palavra para #resolve",
    "CAM_WIDGET_BPMN_VIEWER_ERROR": "Não foi possível renderizar o diagrama:",
    "CAM_WIDGET_BPMN_VIEWER_LOADING": "Carregando diagrama",
    "CAM_WIDGET_COPY": "Clique para copiar '{{value}}'",
    "CAM_WIDGET_COPY_LINK": "copie o link para a localização atual",
    "CAM_WIDGET_CMMN_VIEWER_ERROR": "Não foi possível renderizar o diagrama:",
    "CAM_WIDGET_CMMN_VIEWER_LOADING": "Carregando diagrama",
    "CAM_WIDGET_DMN_VIEWER_ERROR": "Could not render table:",
    "CAM_WIDGET_DMN_VIEWER_LOADING": "Carregando tabela",
    "CAM_WIDGET_FOOTER_TIMEZONE": "Data e Hora serão exibidas no fuso horário:",
    "CAM_WIDGET_FOOTER_POWERED_BY": "Fornecido por",
    "CAM_WIDGET_HEADER_TOGGLE_NAVIGATION": "Toggle navigation",
    "CAM_WIDGET_HEADER_MY_PROFILE": "My profile",
    "CAM_WIDGET_HEADER_SIGN_OUT": "Sign out",
    "CAM_WIDGET_HEADER_SMALL_SCREEN_WARNING": "This application is conceived for larger screens.",
    "CAM_WIDGET_SEARCH_MATCH_TYPE": "of the criteria are met.",
    "CAM_WIDGET_SEARCH_MATCH_TYPE_ANY": "any",
    "CAM_WIDGET_SEARCH_MATCH_TYPE_ALL": "all",
    "CAM_WIDGET_SEARCH_TOTAL_NUMBER_RESULTS": "Total number of results",
    "CAM_WIDGET_SEARCH_VARIABLE_CASE_VALUE": "value",
    "CAM_WIDGET_SEARCH_VARIABLE_CASE_NAME": "name",
    "CAM_WIDGET_SEARCH_VARIABLE_CASE_ATTRIBUTE": "For Variables, ignore case of ",
    "CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_SET_NULL": "Set value to \"null\"",
    "CAM_WIDGET_VARIABLES_TABLE_PLACEHOLDER_VALUE": "Value of the variable",
    "CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_DEFAULT_VALUE": "Re-set to previous or default value",
    "CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_UPLOAD": "Upload a new file",
    "CAM_WIDGET_VARIABLES_TABLE_NULL": "<null>",
    "CAM_WIDGET_VARIABLES_TABLE_EDIT_VARIABLE": "Edit the variable",
    "CAM_WIDGET_VARIABLES_TABLE_DELETE_VARIABLE": "Delete the variable",
    "CAM_WIDGET_VARIABLES_TABLE_SAVE_VARIABLE": "Save the variable",
    "CAM_WIDGET_VARIABLES_TABLE_REVERT_VARIABLE": "Revert the variable",
    "CAM_WIDGET_VARIABLES_TABLE_NAME": "Name",
    "CAM_WIDGET_VARIABLES_TABLE_TYPE": "Type",
    "CAM_WIDGET_VARIABLES_TABLE_VALUE": "Value",
    "CAM_WIDGET_VARIABLES_TABLE_DELETE": "Delete",
    "CAM_WIDGET_VARIABLES_TABLE_ABORT": "Abort",
    "CAM_WIDGET_VARIABLES_TABLE_DIALOGUE": "Are you sure that you want to delete '{{name}}'",
    "CAM_WIDGET_VARIABLE_DIALOG_INSPECT": "Inspect {{ name }} variable",
    "CAM_WIDGET_VARIABLE_DIALOG_LABEL_OBJECT_TYPE": "Object type name:",
    "CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZATION": "Serialization Data Format:",
    "CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZED_VALUE": "Serialized value",
    "CAM_WIDGET_VARIABLE_DIALOG_BTN_CLOSE": "Close",
    "CAM_WIDGET_VARIABLE_DIALOG_BTN_CHANGE": "Change",
    "CAM_WIDGET_VARIABLE_NULL": "<null>",
    "CAM_WIDGET_VARIABLE_SET_VALUE_NULL": "Set value to \"null\"",
    "CAM_WIDGET_VARIABLE_VALUE": "Value of the variable",
    "CAM_WIDGET_VARIABLE_UNDEFINED": "<undefined>",
    "CAM_WIDGET_VARIABLE_RESET": "Re-set to previous or default value",
    "CAM_WIDGET_STRING_DIALOG_TITLE": "Inspect \"{{ name }}\" variable",
    "CAM_WIDGET_STRING_DIALOG_LABEL_VALUE": "Valor",
    "CAM_WIDGET_STRING_DIALOG_LABEL_CLOSE": "fechar",
    "LINKS": "Links",
    "PROFILE": "Perfil",
    "EDIT_PROFILE": "Editar perfil",
    "CHANGE_PASSWORD": "Change password",
    "EDIT_YOUR_PROFILE": "Editar seu perfil",
    "FIRST_NAME": "Primeiro Nome",
    "LAST_NAME": "Último nome",
    "EMAIL": "Email",
    "UPDATE": "Atualizar",
    "CHANGE_YOUR_PASSWORD": "Change your password",
    "CURRENT_PASSWORD": "Senha Atual",
    "NEW_PASSWORD": "Nova Senha",
    "CONFIRM_NEW_PASSWORD": "Confirma sua senha",
    "PASSWORD_NOT_MATCHING": "A Nova senha e a confirmação não são iguais",
    "GROUPS": "Grupos",
    "USERNAME": "Nome do Usuário",
    "CHANGES_SAVED": "Alterações Salvas",
    "ERROR_WHILE_SAVING": "Error while saving",
    "PASSWORD_CHANGED": "Senha alterada",
    "ERROR_WHILE_CHANGING_PASSWORD": "Error while changing password",
    "USERNAME_FOR_AUTHENTICATION": "Nome do Usuário para autenticação: {{username}}",
    "APPLICATIONS": "Aplicações",
    "COCKPIT": "Cockpit",
    "TASKLIST": "Tasklist",
    "ADMIN": "Admin",
    "DOCUMENTATION": "Documentação",
    "DOCUMENTATION_DESCRIPTION": "Documentação do Usuário Camunda webapps",
    "PASSWORD_POLICY_TOOLTIP": "Sua senha deve ter pelo menos:",
    "PASSWORD_POLICY_TOOLTIP_PARTIAL": "Sua senha não tem alguns critérios:",
    "PASSWORD_POLICY_TOOLTIP_ERROR": "Um erro ocorreu durante a validação da senha.",
    "PASSWORD_POLICY_LENGTH": "{{minLength}} letras",
    "PASSWORD_POLICY_LOWERCASE": "{{minLowerCase}} letras minúsculas",
    "PASSWORD_POLICY_UPPERCASE": "{{minUpperCase}} letras maiúsculas",
    "PASSWORD_POLICY_DIGIT": "{{minDigit}} digitos",
    "PASSWORD_POLICY_SPECIAL": "{{minSpecial}} caracteres especiais"
  }
}
